# Generated by Django 3.2.9 on 2021-12-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('social_id', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'SocialLogin',
            },
        ),
    ]
