# Generated by Django 3.2.9 on 2021-11-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=100, unique=True)),
                ('userArea', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=50, unique=True)),
                ('ratingScore', models.IntegerField(default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('userBank', models.CharField(max_length=50, null=True)),
                ('bankNum', models.IntegerField(null=True)),
                ('userNumber', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
