# Generated by Django 3.2.9 on 2021-12-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
