# Generated by Django 3.2.9 on 2021-11-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.IntegerField()),
                ('totalPplCnt', models.IntegerField()),
                ('joinPplCnt', models.IntegerField()),
                ('startPeriod', models.DateField()),
                ('endPeriod', models.DateField()),
                ('deliveryMethod', models.CharField(max_length=10)),
                ('detailContent', models.CharField(max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api_user.user')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
