# Generated by Django 3.2.9 on 2021-12-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_area', models.CharField(max_length=128)),
                ('user_nick', models.CharField(max_length=128, unique=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('user_bank', models.CharField(blank=True, max_length=32, null=True)),
                ('banknum', models.IntegerField(blank=True, null=True)),
                ('user_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('social_id', models.ForeignKey(db_column='social_id', on_delete=django.db.models.deletion.CASCADE, to='api_user.sociallogin')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
