# Generated by Django 3.2.9 on 2021-11-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='joinPplCnt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='startPeriod',
            field=models.DateField(auto_now_add=True),
        ),
    ]
